[package]
name = "extract_types"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
